### ISSUE TITLE
Align method not finding grid

### ISSUE THREAD

**Issue by rcbyron** [randomjohnnyh/brickpop#1]
Hi, I'd really like to try this out, but it seems the align method is having a lot of trouble. It takes a proper screenshot of my game, but the align method can't find the board. Any ideas? I'm not sure how the coordinate system is set up, but could I just pass in the pixel coordinate of the top-left block and the square size (~30pixels)?

Input:
my_console$ java brickpop.Main

Output:
1280 800
common: 0
Best align: 0 -1
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at brickpop.Capture.align(Capture.java:108)
	at brickpop.Capture.convertGrid(Capture.java:174)
	at brickpop.Main.main(Main.java:12)

**Update:**
FYI I set the background color to 0xf5ebdd (which I believe is correct)

**Comment by randomjohnnyh** [comment]
Maybe Java's Robot is not accurately capturing the colors. There's very little documentation on this, so maybe you could write the screenshot to a file and then check it manually.

**Comment by rcbyron** [comment]
So I did what you said and I believe I fixed the alignment/color issue.

It's very cool to see the program running.
However, now the algorithm doesn't seem to be finding complete solutions?
It gets very close, but usually 1 or 2 colors are left over after the first level.

Is this a fault in the algorithm?

Here's the output:
Iter: 9 len: 0
Best: 2108
#moves: 10
CLICKING
16248804
1920 1080
common: 79
Best align: 1 1
common: 7
Best align: 1 1
x 876
x 955
y 157
y 164
2
2
0 1 
2 0 
2
2
Iter: 0 len: 0
Best: 0
NO SOL

Thanks,
Connor
